### ISSUE TITLE
Make site selector more visible

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#149] opened 2024-05-03 18:58 UTC
Site selector is hard to find, it's located at the bottom/end of the left sidebar. We should move it another place to make it more visible.

<img width="1306" alt="Screenshot 2024-05-03 at 2 55 45 PM" src="https://github.com/BeaconCMS/beacon_live_admin/assets/36407/e06e6e24-6308-4e57-be4a-c5d249c0690e">

**Comment by brzpegasus** [comment] 2024-06-13 16:34
Closing as duplicate of #148.

**Closed by brzpegasus** 2024-06-13 16:34 UTC
Labels: enhancement, ux
