### ISSUE TITLE
BUG: Media Library crashes in production

### ISSUE THREAD

**Issue by justinbkay** [BeaconCMS/beacon_live_admin#94] opened 2023-11-24 17:22 UTC
With a site that is build as a release, media can be loaded, but at some point this issue starts happening.  Best guess is the next visit to the Media Library after you've loaded initial media.

Go to the Admin UI > Click on Media Library > The page loads, but then crashes repeatedly.  You get the "Can't find the internet message" over and over and over.  Unable to find the page for each item in the media library.

```
    15:49:50.078 [error] GenServer #PID<0.6042.0> terminating
    ** (RuntimeError) failed to find a page for URL https://<mydomain>/beacon_assets/mysite/media_name.webp

    (beacon_live_admin 0.1.0-dev) lib/beacon/live_admin/page_live.ex:107: Beacon.LiveAdmin.PageLive.lookup_page!/2
    (beacon_live_admin 0.1.0-dev) lib/beacon/live_admin/page_live.ex:40: Beacon.LiveAdmin.PageLive.mount/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/utils.ex:394: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
    (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:1041: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
```

**Comment by leandrocp** [comment] 2024-01-02 14:17
@justinbkay thanks for the report, it's related to how pages are dynamically loaded in admin. I'll work on a fix soon.

**Comment by APB9785** [comment] 2024-04-05 19:12
Hi @justinbkay I'm looking into this issue and think it may have been resolved in a recent commit;  I cannot reproduce the crash anymore.  Can you confirm if you are still experiencing it with the latest Beacon changes?

**Comment by justinbkay** [comment] 2024-04-05 20:45
Hi @APB9785 I haven't seen that error since I submitted this ticket.

**Comment by APB9785** [comment] 2024-04-05 20:48
Awesome, thanks for the feedback and for using Beacon!

**Closed by APB9785** 2024-04-05 20:48 UTC
Labels: bug
